server:
  port: 5000
spring:
  application:
    name: TASKER-GATEWAY-SERVER
  cloud:
    gateway:
      discovery:
         locator:
          enabled: true
      routes:
        - id: TASKER-USER-SERVICE
          uri:
            lb://TASKER-USER-SERVICE
          predicates:
            - Path=/auth/**,/users/**,/api/users/**,/
        - id: TASKER-TASK-MICROSERVICE
          uri:
            lb://TASKER-TASK-MICROSERVICE
          predicates:
            - Path=/api/tasks/**,/tasks/**
        - id: TASKER-SUBMISSION-SERVICE
          uri:
            lb://TASKER-SUBMISSION-SERVICE
          predicates:
            - Path=/api/submissions/**,/submissions/**
        - id: swagger_route
          uri: http://localhost:5000
          predicates:
            - Path=/swagger-ui.html, /swagger-ui/**, /v3/api-docs/**, /swagger-resources/**, /api-docs/**, /aggregate/**


      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"


eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/


springdoc:
  api-docs:
    path: "/api-docs"
  swagger-ui:
    path: "/swagger-ui.html"
#  swagger-ui-config:
#    urls:
#      - url: /v3/api-docs
#        name: API Docs
#      - url: /swagger-ui
#        name: Swagger UI
#      - url: /swagger-resources
#        name: Swagger Resources
#      - url: /api-docs
#        name: API Docs
#      - url: /aggregate
#        name: Aggregate Docs
