spring:
  application:
    name: tasker-user-service


  data:
    mongodb:
        uri: mongodb+srv://vicktord007:lwAO7FDd0zDsnQpW@cluster0.j7wa8.mongodb.net/tasker-user-db?retryWrites=true&w=majority&appName=Cluster0


server:
  port: 5001

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/